# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import private_media.storages
import spaces_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(storage=private_media.storages.PrivateMediaStorage(), upload_to=spaces_blog.models.file_upload_path, verbose_name='Image'),
        ),
    ]
